-- GENERAR EL DDL

CREATE DATABASE proyecto_turnos;

USE proyecto_turnos;

-- Tabla TURNO
CREATE TABLE TURNO (
    IDTURNO INT PRIMARY KEY AUTO_INCREMENT,
    IDPACIENTE INT,
    IDMEDICO INT,
    IDEMPLEADO INT,
    IDESPECIALIDAD INT,
    FECHA DATETIME,
    CANCELACION DATETIME DEFAULT NULL
);

-- Tabla PACIENTE
CREATE TABLE PACIENTE (
    IDPACIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100) DEFAULT 'USUARIO_UNKNOW',
    TELEFONO VARCHAR(20) NOT NULL,
    CORREO VARCHAR(100) UNIQUE NOT NULL
);

-- Tabla EMPLEADO
CREATE TABLE EMPLEADO (
    IDEMPLEADO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    TELEFONO VARCHAR(20),
    CORREO VARCHAR(100),
    IDCLINICA INT
);

-- Tabla DUENO
CREATE TABLE DUENO (
    IDDUENO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    CORREO VARCHAR(100),
    TELEFONO VARCHAR(20)
);

-- Tabla ESPECIALIDAD
CREATE TABLE ESPECIALIDAD (
    IDESPECIALIDAD INT PRIMARY KEY AUTO_INCREMENT,
    TIPO VARCHAR(50)
);

-- Tabla CLINICA
CREATE TABLE CLINICA (
    IDCLINICA INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    DIRECCION VARCHAR(255),
    TELEFONO VARCHAR(20)
);

-- Tabla MEDICO
CREATE TABLE MEDICO (
    IDMEDICO INT PRIMARY KEY AUTO_INCREMENT,
    IDCLINICA INT,
    CAPACIDAD INT,
    DISPONIBLE BOOLEAN
);



-- FOREIGN KEYS DEFINITION

-- EMPLEADO

ALTER TABLE EMPLEADO
    ADD CONSTRAINT FK_EMPLEADO_CLINICA
    FOREIGN KEY (IDCLINICA) REFERENCES CLINICA(IDCLINICA);
    
-- MEDICO
ALTER TABLE MEDICO
    ADD CONSTRAINT FK_MEDICO_CLINICA
    FOREIGN KEY (IDCLINICA) REFERENCES CLINICA(IDCLINICA);
    
-- TURNO

ALTER TABLE TURNO
    ADD CONSTRAINT FK_TURNO_PACIENTE
    FOREIGN KEY (IDPACIENTE) REFERENCES PACIENTE(IDPACIENTE);

ALTER TABLE TURNO
    ADD CONSTRAINT FK_TURNO_MEDICO
    FOREIGN KEY (IDMEDICO) REFERENCES MEDICO(IDMEDICO);

ALTER TABLE TURNO
    ADD CONSTRAINT FK_TURNO_EMPLEADO
    FOREIGN KEY (IDEMPLEADO) REFERENCES EMPLEADO(IDEMPLEADO);
    
ALTER TABLE TURNO
    ADD CONSTRAINT FK_TURNO_ESPECIALIDAD
    FOREIGN KEY (IDESPECIALIDAD) REFERENCES ESPECIALIDAD(IDESPECIALIDAD);
   

